# Generated by Django 5.2.13 on 2026-05-01 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_donation', models.BooleanField(default=True)),
                ('new_message', models.BooleanField(default=True)),
                ('pickup_updates', models.BooleanField(default=True)),
                ('low_stock', models.BooleanField(default=True)),
                ('weekly_report', models.BooleanField(default=False)),
                ('email_digest', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
