# Generated by Django 5.2.13 on 2026-04-30 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_donation_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-timestamp']},
        ),
    ]
