# Generated by Django 5.2.13 on 2026-04-30 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryitem_distributed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impactmetric',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['id']},
        ),
    ]
